# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a952e8ed27f1a70e97c9c91c70b2e246357c00a311f1c0aafbba122bba493aa5128fd881437c3ae23e3c7c9c4d357034029cbc9400152c13f3cf7e6c923d28a

test:
  secret_key_base: b3b8627a864766e3fff5b6b47d3290eb09972ac4d3fad39c19521c4b00418598ec53842119be2daa749cbcbc281191644a4db42f8707995402842a70f871e57e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
